language: node_js
node_js: stable
sudo: required
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
- npm test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test:sl; fi
env:
  global:
    - secure: >-
        KWxJU6OvJVWgGodzaKdFgofT015zFTJX2K+gkNJNzcjA9rxxCUI9NepcJVoQJbzKd4Y0AqusfEFCnqdjrwk0YWWqSO4FYDxj0bv8hv3cp3DHNsQJks/e7pajoaJsi8fZSzv0V2qDbhFCzPPBzjy9DQzdm4gPFKs/XKxFTcxhYqgEFz2Zj+BuEC795ENeyFH1CwOPLgsYR2gnyFzY/szGI4RoaAsTJn2xXGGHF9c3xik27Dyp5WbjumPiBMaATyuSDYf44x2J3tHDmg/7CHGg5Fo8Hx+0kuV3gH3xvmq7N5tA///MaRtxHCKlA3SsAaowtJ6eGoCipJN1bFeM3EVTX+0Pyv1UPo1xiEMrQEQbwJmVDykk9esTzUHOgaz9Ky3IWn9ilxg/+5FiOGk5daeL/xEgB9LHEv4k8NPYh9KAVLO3xyjkZAj40skfW+ReH6PArqnhcUR0u2yJ5iEnKKwQs6oQ0nSwBG5tKprk0Sed5b8fnfZJLyO1/Mf1mTuqaQyZ9HWCZUHkyTc+jIRDt2eBMH22urV46IkEl7FYj9EmcfVnKnTSPiWe2OrAdY9ONwgujEsJn4H7aPpvCeLFouKN8YSO7nf90u3r9FR0MiaRqfwqU+ZKYyQSByfHaOvjZpefdU3QEKRiEQQNOXzeB3se9wSM+QbNfxKIHltnEVBg21c=
    - secure: >-
        iCrZrL90OI64iHy2j03WPWGedT1Jj871auhs9GxoW4BaY7WuXxAKbKwot9Wv9pPV4JPSdbzhAdTD50L2qlZHqj5+8BXFBJ6X68rEnEDBnu82BA7hEft+BoSPQdxeZ0sQeaab/A8f5JO++drvG2zISlvCnrMIAFlKOn+8bXAdM8QCDEJJGqB7G8XaCawkNxE3j8GzMgCQNFQteQQh+xQS/eRNV6PQe/lr9DVQcsHi9t+dxHr8BgLghfOVDDctykSLaCzwM7ww4ogwHbbr0zmHZ3pkOZBML1WTwWYTPTsGuaRGUYyCxFe//q0s5Ug6pNhwNqudViTiqJzQEnLXSuiQMe4dQi8ZVD3UqzXG8EhSm3fKv4hMnLlNa6Q/hXuKoZOhl9rA2l7szD+LhoF5xEx+WHGar29qdLiL20NaxEbKJNHyJ6LmzM8LZGlVUCBYjvOfagzZC2bCM89tHMpQoCLLbbiy0BdiZitj4nD8Le1SEyGCOKvuHPLz3UGpkybQ/X1X3hum1mnw3liMg03yOwT+40oNiMhZtF4dHmoIddC/ChO8LdviOlS8JETwEjCzUnNXFwupueLBhdntet4fA+aLp3M7R9tuWLxaAPu98Wao9FCKEZVkbXUYXzqfiL02ML0bpZ6YBsX1r8v/6t9hroiXHKmB/eEtZmYWPdtxs91dWsM=
