/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   websocket-history.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

declare namespace ApiElements {

  /**
   * A web socket connections history view for ARC
   *
   * ### Example
   *
   * ```html
   * <websocket-history items="[...]"></websocket-history>
   * ```
   *
   * ### Styling
   *
   * `<websocket-history>` provides the following custom properties and mixins
   * for styling:
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--websocket-history` | Mixin applied to the element | `{}`
   * `--arc-font-subhead` | Mixin applied to the element's title | `{}`
   * `--websocket-history-time-label` | Color of the date-time label | `rgba(0, 0, 0, 0.54)`
   * `--websocket-history-date-time` | Mixin applied to the `date-time` element | `{}`
   */
  class WebsocketHistory extends PolymerElement {

    /**
     * List of history items to render
     */
    items: any[]|null|undefined;

    /**
     * Called when the user click on the `connect` button
     */
    _openUrl(e: any): void;
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "websocket-history": ApiElements.WebsocketHistory;
  }
}

export {};
